# baseURL
@baseURL = http://localhost:3000

###
# Find All Users
GET {{ baseURL }}/users

###
# Find User By Id
GET {{ baseURL }}/users/1

###
# Create User
POST {{ baseURL }}/users
Content-Type: application/json

{
	"uid": "tommy@shelby.com",
	"name": "thamuz shelby",
	"businessName": "kokein",
	"businessNumber": "02222222222222222",
	"phoneNumber": "088888888888888888888",
	"address": "jalan jalan ke pasar minggu",
	"IDCard": "NIK ges yak"
}

###
# Modify User By Id
PUT {{ baseURL }}/users/1
Content-Type: application/json

{
	"uid": "57aJHLzM0nW2oixwD90DEFWoeR33",
	"name": "thamuz shelby",
	"businessName": "kokein",
	"businessNumber": "02222222222222222",
	"phoneNumber": "088888888888888888888",
	"address": "jalan jalan ke pasar minggu",
	"IDCard": "NIK ges yak"
}

###
# Delete User By Id
DELETE {{ baseURL }}/users/1
